name: riverpod_repo
description: A Lib to build Riverpod providers based on the reposirory interfaces.
version: 4.7.0
homepage: https://dilan.me
repository: https://github.com/chaturadilan/riverpod_repo_generator

environment:
  sdk: ^3.10.8
  flutter: ">=3.35.0"

topics:
  - riverpod
  - code-generation
  - repository-pattern
  - flutter
  - dart

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.0
  source_gen: ^4.0.0
  recase: ^4.1.0
  analyzer: ">=7.6.0 <9.0.0"
  riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  riverpod_generator: ^4.0.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
